#!/bin/sh
# Copyright Matthew Wall, all rights reserved
# cgi stub to reply to acurite internet bridge
#
# Thanks to Rich at modern toil for the original implementation

# reply to the bridge with output like we get from the acu-link.com server
echo "Content-type: text/html"
echo
echo '{ "success": 1, "checkversion": "126" }'

# get the data as a single string
POSTDATA=$(cat | tr -d ' ')

# dump the output to file for debugging
#echo "$POSTDATA" > /var/tmp/bridge-data

SERVER_PORT=9999

# dump the output to a socket
#echo "$POSTDATA" | nc -l -k $SERVER_PORT

# send data to the interceptor driver
curl -s -d "$POSTDATA" http://localhost:${POST_DATA}/messages/ > /dev/null

# send the data to acurite's acu-link web server if you want that to be updated
#curl -s -d "$POSTDATA" http://acu-link.com/messages/ > /dev/null
